name: rega
description: "REGA - Quiz App with Paid Subscriptions"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Prototype
      fonts:
        - asset: assets/fonts/Prototype.ttf
    - family: PeshangDes
      fonts:
        - asset: assets/fonts/Peshang_Des_2.ttf
